import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import { NavigationPill } from "@/components/navigation-pill";

const font = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "container mx-auto")}>
        <NavigationPill />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
