import type { Metadata } from "next";

import "./globals.scss";
import "@/styles/variables.scss";

import "open-props/style";
import "open-props/colors-hsl";
import "open-props/animations";
import "open-props/easings";

import { NavPill } from "@/components/nav-pill";
import { BotInset } from "@/components/insets/bot-inset";
import { TopInset } from "@/components/insets/top-inset";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <TopInset /> */}
        <NavPill />
        <div className="">{children}</div>
        {/* <BotInset /> */}
      </body>
    </html>
  );
}
