import { Footer } from "@/components/footer";
import BackButton from "./_components/back-button";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body>
      <BackButton />
      {children}
      <Footer />
    </body>
  );
}
